### ISSUE TITLE
MaRaCluster parameters for high mass accuracy data

### ISSUE THREAD

**Issue by ArminGuntram** [statisticalbiotechnology/maracluster#10]
Hi,
I'm working on a plant proteome dataset and I'm currently looking at the outputs from MaRaCluster, Spectra-cluster and MS-cluster. 
The data I'm working with is unfractionated and is considered high mass accuracy in both MS1 and MS2. The MS1 tolerance is 0.005 and the MS2 is 0.01 (m/z units).

Right now I'm playing around with the --precursorTolerance and --clusterThresholds and seeing how they affect the output. What parameters would you suggest for a high accuracy dataset like this?

Thank you in advance,
-Armin

**Comment by MatthewThe** [comment]
Hi Armin,

The defaults will probably be fine, though you could try explicitly setting --precursorTolerance to "0.005Da". The --clusterThresholds will just give you several output files at different thresholds, typically the *.clusters_p10.tsv gives us the best results, though this depends a bit on the number of original spectra (if you have only a few thousand spectra, you could try the *.cluster_p5.tsv as well).

Currently we are not making ultimate use of high-accuracy MS2 data, choosing to bin the data in 1Da bins. We have tried using smaller bins for high-accuracy MS2 data, but this usually did not give much better results.

Hope that helps, let me know if you have any more questions.
