### ISSUE TITLE
Setting CMAKE_INCLUDE/LIBRARY_PATH preceeds BOOST_ROOT

### ISSUE THREAD

**Issue by Micket** [statisticalbiotechnology/maracluster#11]
For a module system that's present on almost every HPC system, FindBoost relies on BOOST_ROOT.
Perhaps this could be argued to be a bug or bad design in FindBoost.cmake, but prefixing /usr/include will make all findboost find the wrong installation.

I dont think these should be set anyway, so removing them is an easy fix.

The problematic lines are:
```cmake
set(CMAKE_INCLUDE_PATH /usr/include ${CMAKE_INCLUDE_PATH})
set(CMAKE_LIBRARY_PATH /usr/lib /usr/lib64 ${CMAKE_LIBRARY_PATH})
```
Line 66-67 in CommonCMake.txt

**Comment by MatthewThe** [comment]
That sounds reasonable, I will check if removing these two lines does not break anything on our build systems.
