### ISSUE TITLE
mzML, idXML parsing issue for OpenMS Adapter

### ISSUE THREAD

**Issue by Leon-Bichmann** [statisticalbiotechnology/maracluster#12]
Let me know when you have fixed the problem that we had with OpenMS test mzML files as well as the SpectrumReference Identifiers ( "spectrum=" or "scan=" or "index=").

Best,
Leon

**Comment by MatthewThe** [comment]
I've just made some fixes to the code that should address both issues. Could you try replacing your maracluster binary with this one (built for OSX):
[maracluster.zip](https://github.com/statisticalbiotechnology/maracluster/files/1631611/maracluster.zip)

If all the tests work, I can create a new release containing these fixes.

**Comment by Leon-Bichmann** [comment]
yep it is working for me, however there is another test mzml file in the OpenMS directory:
OpenMS/src/tests/topp/THIRDPARTY/spectra.mzML

that it didnt work for, maybe you can quickly check if you see the problem.

**Comment by MatthewThe** [comment]
What error did you get? It seems to work fine on my Ubuntu machine, I can check on OSX tomorrow.

**Comment by Leon-Bichmann** [comment]
Hey, I am getting the following error running the Adapter:

```
Splitting spectra by precursor Mz
Accumulating peak counts and precursor Mzs
  Processing OpenMS_sample/spectra.mzML (50%).
  Processing OpenMS_sample/spectra1.mzML (100%).
Writing peak counts to file
Finished writing peak counts to file
Estimated number of pair comparisons: 0
Dividing spectra in 0 bins of ~2 CPU hours each.
  Processing OpenMS_sample/spectra.mzML (50%).
  Processing OpenMS_sample/spectra1.mzML (100%).
Exception caught: vector
MaRaCluster problem. Aborting!
```

**Comment by MatthewThe** [comment]
Thanks for the output.

I cannot find spectra1.mzML in the folder you specified, did you just make a copy of spectra.mzML and named it spectra1.mzML? Anyhow, the error message should be made more informative than this..

**Comment by Leon-Bichmann** [comment]
ah yes sorry, I just copied the spectra file  (actually I think it was the spectra_comet.mzML) and named it spectra1.. when I run it from the executable i get:
segmentation fault 11
anyhow no pressure, if you could test it tomorrow on OSX it should be fine

**Comment by MatthewThe** [comment]
Hmm, I followed your steps and it still works fine on my machine. The weird part is that you get `Estimated number of pair comparisons: 0`, while I get `Estimated number of pair comparisons: 3`. My guess is that the paths to (one of) the mzML files is somehow not resolved correctly. Relative paths should be with respect to the directory where maracluster is run from.

Could you try to use absolute paths in the text file with the file paths?

**Comment by Leon-Bichmann** [comment]
ok tested it again and it worked. Then I will include the new binary for the next OpenMS relase.
