### ISSUE TITLE
PSMs made by Crux - however scans not clustered by Maracluster 

### ISSUE THREAD

**Issue by ArminGuntram** [statisticalbiotechnology/maracluster#14]
Hi, 

I'm finding several thousands of scans that are confidently identified peptides(using crux pipeline), but the scans are not present in the clustered output. The absent scans are not specific to one sample. All of the omitted scans start late in the run (retention times starting at 7979 sec, continue through to end of run 10736 sec).

I have rerun Maracluster and the same output is produced. I confirmed that the scans were indeed present in the .mgf files that I'm using as input for Maracluster. 

I'v observed a similar omission pattern from the output of MScluster, however Spectra-cluster does include these scans in its clustered output. Is there a filter option that I need to adjust or something obvious that I'm missing? Right now I'm running Maracluster with a --precursorTolerance of 0.005Da and all other program options at default.

Running MaraCluster version 0.03.1 on Windows 10, 64-bit

Please advise and let me know if there are any other detail I can provide?
-Thank you

**Comment by MatthewThe** [comment]
Thanks for the bug report, from your description I can't find anything obviously wrong. Could you perhaps share the mgf files and your MaRaCluster output? My e-mail address is matthew [dot] the [at] scilifelab [dot] se.

**Comment by MatthewThe** [comment]
For future reference, here is a python script that can convert the scan indices to scan numbers for mgf input:
[update_scan_nrs.py.zip](https://github.com/statisticalbiotechnology/maracluster/files/1832435/update_scan_nrs.py.zip)

Note that one would still have to use the cluster file with scan indices to create consensus spectra.
