### ISSUE TITLE
Interpreting pvalue tree

### ISSUE THREAD

**Issue by ArminGuntram** [statisticalbiotechnology/maracluster#16]
Hi,

What are the columns in the output files '*.pvalue_tree.tsv' and '*overlap.pvalue_tree.tsv'

From the help doc I assume: "File containing the clustering tree result as a list of merged scannrs with corresponding p-value"

Also, is there a way I can access/print to file the clustering matrix?

Thanks,
-Armin

**Comment by MatthewThe** [comment]
Each of the rows represents a link in the hierarchical clustering tree:
<file_idx_1> <scannr_1> <file_idx_2> <scannr_2> <p-value>

The distance matrix cannot be written to a file, as it is consumed "on the fly".

**Comment by MatthewThe** [comment]
Added to the FAQ (https://github.com/statisticalbiotechnology/maracluster/wiki/FAQ)
