### ISSUE TITLE
Building locally

### ISSUE THREAD

**Issue by andrewjmc** [statisticalbiotechnology/maracluster#18]
Hello,

I am having difficulty building maracluster locally on HPC without admin rights (I cannot install from the pre-built files).

The advice given seems insufficient, as there are multiple "sudo" commands in the Centos build script. I have tried removing these, and adding the -g flag to `quick_build.sh`. However, this does not seem to result in the -g flag being passed to the Centos build script. Hard-coding the -g flag also did not seem to stop it trying to built the gui version.

This then fails, perhaps because the HPC does not have the Qt libraries installed.

It also cannot find rpmbuild on HPC, and creating an RPM will be useless to me since I cannot install RPMs.

As an HPC-using bioinformatician, I would recommend as far as possible distributing packages as locally executable tar.gz files. Any chance of releasing?

Thanks,

Andrew

**Comment by MatthewThe** [comment]
I think it should be possible to create a tar.gz for maracluster, I'll give it a try tomorrow.

**Comment by andrewjmc** [comment]
Thanks!
