### ISSUE TITLE
Index out of bounds (both MGF and mzML)

### ISSUE THREAD

**Issue by kesinger** [statisticalbiotechnology/maracluster#23]
I'm having the same problem as in https://github.com/statisticalbiotechnology/maracluster/issues/19 .  I'm on version 1.01.1 (Apr 23 2020 13:12:07), which I downloaded from the Releases tab. 

This happens on both MGF and mzML input.  Original run was:
```
maracluster batch -b filelist
```
And consensus run was:
```
 maracluster consensus -l maracluster_output/MaRaCluster.clusters_p10.tsv -o maracluster_output/consensus.ms2 
```

No output is produced. I have not yet tried building from source.

**Comment by MatthewThe** [comment]
Thanks for reporting this!

Would you be able to share some input files that produce this error?

**Comment by MatthewThe** [comment]
Ah, yes absolutely. I somehow thought I had created a new release for this fix already..

**Comment by MatthewThe** [comment]
I just created a new release, let me know if you still run into issues.
