### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by JannikSchneider12** [statisticalbiotechnology/maracluster#28]
Hello,

I wanted to try maracluster but had issues with the installation. I am not very familiar with Linux or C but maybe you have an idea?
I am using WSL and I also installed Proteowizard from the github repo. Then I cloned this repo and tried to run the installation script with "bash ./quickbuild.sh", but this error occured:

-- -------------------------------------------------------------------------------
-- Building MARACLUSTER:
-- change a configuration variable with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /usr
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_PREFIX_PATH = /home/jannik/Masterthesis/Maracluster/maracluster/../build/ubuntu64/tools/;/home/jannik/Masterthesis/Maracluster/maracluster/../build/ubuntu64/tools/Qt-dynamic/, /home/jannik/Masterthesis/Maracluster/maracluster/cmake
-- TARGET_ARCH = amd64
-- TOOL CHAIN FILE =
-- PROFILING =
-- -------------------------------------------------------------------------------
-- MARACLUSTER options:
-- FINGERPRINT_FILTER = OFF
-- DOT_PRODUCT = OFF
-- SINGLE_LINKAGE = OFF
-- VENDOR_SUPPORT = OFF
-- -------------------------------------------------------------------------------
--
-- Architecture: amd64
-- Checking packages:
-- Package Boost found at: /home/jannik/Masterthesis/Maracluster/build/ubuntu64/tools/include
-- Zlib found at: /home/jannik/Masterthesis/Maracluster/build/ubuntu64/tools/include; /home/jannik/Masterthesis/Maracluster/build/ubuntu64/tools/lib/libzlib.a
-- Found pwiz include directory: /home/jannik/Masterthesis/Maracluster/build/ubuntu64/tools/include
CMake Error at /home/jannik/Masterthesis/Maracluster/maracluster/cmake/FindProteoWizard.cmake:15 (message):
  PWIZ_DATA_MSDATA_LIBRARY library not found
Call Stack (most recent call first):
  /home/jannik/Masterthesis/Maracluster/maracluster/cmake/FindProteoWizard.cmake:24 (_pwiz_find_library)
  /home/jannik/Masterthesis/Maracluster/maracluster/src/CMakeLists.txt:38 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jannik/Masterthesis/Maracluster/build/ubuntu64/maracluster-gui/CMakeFiles/CMakeOutput.log".
make maracluster-gui (this will take few minutes).....make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'package'.  Stop.
make: *** No rule to make target 'install'.  Stop.
cp: cannot stat '/home/jannik/Masterthesis/Maracluster/maracluster/../build/ubuntu64/maracluster/mar*.deb': No such file or directory

Thanks for your time and help

**Comment by MatthewThe** [comment]
Nice that you want to try out maracluster!
Is there a reason why you don't want to use the precompiled binaries: https://github.com/statisticalbiotechnology/maracluster/releases/tag/rel-1-04

If you really want to build from source, the problem seems to have been the installation of ProteoWizard.
The `quickbuild.sh` script attempted to install ProteoWizard but it looks like something went wrong (it will not use your installed version of ProteoWizard because maracluster needs the libraries which don't come with the regular ProteoWizard installation).
There should be a file called `pwiz_installation.log` in your build directory. If you share that file, I can try to help you further.

**Comment by JannikSchneider12** [comment]
Hey,

Thank you for the quick answer. So I installed it with the precompiled binaries, created a txt file and tried to run maracluster batch. However at one point it just says "killed". So this is the last output:

Processing pvalue vector 1230001/6051285 (20%).
Processing pvalue vector Starting MinHeap clustering
  Loading new edges.
1240001/6051285 (20%).
It. 20000: minRow = 14 27722, minCol = 39 30299, minEl = -33.9852, edgesLeft = 23409865
Killed

**Comment by MatthewThe** [comment]
This usually means that you ran out of memory. You can try prepending your command by `OMP_NUM_THREADS=<n_threads>`, e.g.
```
OMP_NUM_THREADS=2 maracluster ...
```

**Comment by JannikSchneider12** [comment]
Thank you. I just changed the swap limit in WSL and that worked too :)
