### ISSUE TITLE
local installation on cluster

### ISSUE THREAD

**Issue by ArminGuntram** [statisticalbiotechnology/maracluster#8]
Hi,

I'm having problems trying to create a local installation of this program. I'm working on Red Hat Enterprise Linux Server release 6.8 (Santiago). Please advise

**Comment by MatthewThe** [comment]
We haven't tested the build procedures on Red Hat, but - if you haven't already done so - you could try running one of these installation scripts: `admin/builders/centos64_build.sh` or `admin/builders/centos64_build.sh`.

**Comment by ArminGuntram** [comment]
Hi,

We are encountering a CMakeLists.txt error, there are several files with
the name 'CMakeLists.txt' in the build tree.  Which CMakeLists.txt file
should the builder be finding?

**Comment by MatthewThe** [comment]
CMake should use the CMakeLists.txt in the root directory (https://github.com/statisticalbiotechnology/maracluster/blob/master/CMakeLists.txt), this will subsequently call each of the CMakeLists.txt in the sub-directories.
